FROM python:3.10-slim

WORKDIR /app
COPY ./streamlit_app /app/streamlit_app
COPY ./config /app/config
COPY requirements.txt ./
COPY .env /app/.env

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501
CMD ["streamlit", "run", "streamlit_app/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
