version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: churn_prediction_api
    ports:
      - "8000:8000"
    volumes:
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=file:/app/mlruns

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: churn_prediction_streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api
