FROM python:3.12.6-slim

WORKDIR /app
COPY ./api /app/api
COPY ./config /app/config
COPY ./mlruns /app/mlruns
COPY requirements.txt ./
COPY .env /app/.env

RUN pip install --no-cache-dir -r requirements.txt

ENV MLFLOW_TRACKING_URI=file:/app/mlruns

EXPOSE 8000
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
