services:

  mlflow:
    build:
      context: .
      dockerfile: ./mlflow_server/Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlartifacts:/app/mlartifacts

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlartifacts:/app/mlartifacts
      - ./config:/app/config

  streamlit:
    build:
      context: .
      dockerfile: ./streamlit_app/Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ./config:/app/config
