FROM python:3.10-slim

WORKDIR /app

# copy to WORKDIR root
COPY ./.env .
COPY ./requirements.txt .

# copy to WORKDIR subdirectories
COPY ./config ./config
COPY ./streamlit_app ./streamlit_app

# RUN pip install --no-cache-dir -r requirements.txt
RUN pip install -r requirements.txt

EXPOSE 8501

CMD ["python", "-m", "streamlit", "run", "streamlit_app/app.py", "--server.port=8501", "--server.address=0.0.0.0"]