ARG PYTHON_IMAGE
ARG MLFLOW_SERVER_PORT
ARG MLFLOW_SERVER_ADDRESS

FROM ${PYTHON_IMAGE}

WORKDIR /app

RUN pip install --no-cache-dir mlflow[extras]

EXPOSE 5000

CMD ["mlflow", "server", \
     "--backend-store-uri", "file:/app/mlruns", \
     "--default-artifact-root", "file:/app/mlartifacts", \
     "--host", "${MLFLOW_SERVER_ADDRESS}", \
     "--port", "${MLFLOW_SERVER_PORT}"]
