FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir mlflow[extras]

EXPOSE 5000

CMD ["mlflow", "server", \
     "--backend-store-uri", "file:/app/mlruns", \
     "--default-artifact-root", "file:/app/mlartifacts", \
     "--host", "0.0.0.0", \
     "--port", "5000"]
