FROM python:3.10-slim

WORKDIR /app

# copy to WORKDIR root
COPY ./.env .
COPY ./requirements.txt .

# copy to WORKDIR subdirectories
COPY ./config ./config
COPY ./api ./api

# RUN pip install --no-cache-dir -r requirements.txt
RUN pip install -r requirements.txt

EXPOSE 8000

CMD ['python', '-m', 'uvicorn', 'api.main:app', '--host', '0.0.0.0', '--port', '8000']