ARG PYTHON_IMAGE
ARG API_PORT
ARG API_ADDRESS

FROM ${PYTHON_IMAGE}

WORKDIR /app

# copy to WORKDIR root
COPY ./.env .
COPY ./requirements.txt .

# copy to WORKDIR subdirectories
COPY ./config ./config
COPY ./api ./api

# RUN pip install --no-cache-dir -r requirements.txt
RUN pip install -r requirements.txt

EXPOSE ${API_PORT}

CMD ['python', '-m', 'uvicorn', 'api.main:app', \
    '--host', '${API_ADDRESS}', '--port', '${API_PORT}']